(
    fileIn "$privatePluginPackageInstallPath\\max-{max_version}-usd-examples\\scripts\\max_usd_examples\\init.ms"
    fileIn "$privatePluginPackageInstallPath\\max-{max_version}-usd-examples\\scripts\\max_usd_examples\\usd_export_helper.ms"
    fileIn "$privatePluginPackageInstallPath\\max-{max_version}-usd-examples\\scripts\\max_usd_examples\\usd_export_modifier.ms"
    fileIn "$privatePluginPackageInstallPath\\max-{max_version}-usd-examples\\scripts\\max_usd_examples\\usd_export_scene_helper.ms"
    fileIn "$privatePluginPackageInstallPath\\max-{max_version}-usd-examples\\scripts\\max_usd_examples\\usd_variant_model_asset_helper.ms"
    messageBox "USD Bonus Tools Intialized!"
)